from collections.abc import Generator
from contextlib import contextmanager
from types import TracebackType

from _typeshed import Incomplete

@contextmanager
def capture_exceptions() -> Generator[list[Incomplete]]: ...

class _QtExceptionCaptureManager:
    def __init__(self) -> None: ...
    def start(self) -> None: ...
    def finish(self) -> None: ...
    def fail_if_exceptions_occurred(self, when: Incomplete) -> None: ...

def format_captured_exceptions(
    exceptions: list[
        tuple[type[BaseException] | None, BaseException | None, TracebackType]
    ],
) -> str: ...

class TimeoutError(Exception): ...
class ScreenshotError(Exception): ...
