from _typeshed import Incomplete

VersionTuple = ...
QT_APIS = ...

class _QtApi:
    def __init__(self) -> None: ...
    def set_qt_api(self, api: str) -> None: ...
    def exec(
        self, obj: Incomplete, *args: Incomplete, **kwargs: Incomplete
    ) -> Incomplete: ...
    def get_versions(self) -> tuple[str, ...]: ...

qt_api = ...
