from collections.abc import Callable, Generator
import contextlib
import pathlib
from types import TracebackType
from typing import Literal, Self

from _typeshed import Incomplete
from PySide6.QtCore import QRect, Qt, Signal
from PySide6.QtGui import QKeySequence
from PySide6.QtWidgets import QWidget

from .wait_signal import CallbackBlocker, MultiSignalBlocker, SignalBlocker

class QtBot:
    def __init__(self, request: Incomplete) -> None: ...
    def addWidget(
        self, widget: QWidget, *, before_close_func: Callable[[QWidget], None] = ...
    ) -> None: ...
    def waitActive(
        self, widget: QWidget, *, timeout: int | None = ...
    ) -> _WaitWidgetContextManager: ...
    def waitExposed(
        self, widget: QWidget, *, timeout: int | None = ...
    ) -> _WaitWidgetContextManager: ...
    def waitForWindowShown(self, widget: QWidget) -> bool: ...
    def stop(self) -> None: ...
    def waitSignal(
        self,
        signal: Signal,
        *,
        timeout: int = ...,
        raising: bool = ...,
        check_params_cb: Callable[..., Incomplete] = ...,
    ) -> SignalBlocker: ...
    def waitSignals(
        self,
        signals: list[Signal],
        *,
        timeout: int = ...,
        raising: bool = ...,
        check_params_cbs: list[Callable[..., Incomplete]] = ...,
        order: str = ...,
    ) -> MultiSignalBlocker: ...
    def wait(self, ms: int) -> None: ...
    @contextlib.contextmanager
    def assertNotEmitted(
        self, signal: Signal, *, wait: int = ...
    ) -> Generator[None]: ...
    def waitUntil(
        self, callback: Callable[..., Incomplete], *, timeout: int = ...
    ) -> None: ...
    def waitCallback(
        self, *, timeout: int = ..., raising: bool = ...
    ) -> CallbackBlocker: ...
    @contextlib.contextmanager
    def captureExceptions(self) -> Generator[list[Incomplete], Incomplete]: ...

    capture_exceptions: Callable[..., Generator[list[Incomplete], Incomplete]] = ...
    def screenshot(
        self, widget: QWidget, suffix: str = ..., region: QRect = ...
    ) -> pathlib.Path: ...
    @staticmethod
    def keyClick(*args: Incomplete, **kwargs: Incomplete) -> None: ...
    @staticmethod
    def keyClicks(*args: Incomplete, **kwargs: Incomplete) -> None: ...
    @staticmethod
    def keyEvent(*args: Incomplete, **kwargs: Incomplete) -> None: ...
    @staticmethod
    def keyPress(*args: Incomplete, **kwargs: Incomplete) -> None: ...
    @staticmethod
    def keyRelease(*args: Incomplete, **kwargs: Incomplete) -> None: ...
    @staticmethod
    def keySequence(widget: QWidget, key_sequence: QKeySequence) -> None: ...
    @staticmethod
    def keyToAscii(key: Qt.Key) -> None: ...
    @staticmethod
    def mouseClick(*args: Incomplete, **kwargs: Incomplete) -> None: ...
    @staticmethod
    def mouseDClick(*args: Incomplete, **kwargs: Incomplete) -> None: ...
    @staticmethod
    def mouseMove(*args: Incomplete, **kwargs: Incomplete) -> None: ...
    @staticmethod
    def mousePress(*args: Incomplete, **kwargs: Incomplete) -> None: ...
    @staticmethod
    def mouseRelease(*args: Incomplete, **kwargs: Incomplete) -> None: ...

class _WaitWidgetContextManager:
    def __init__(
        self,
        method_name: str,
        adjective_name: Literal["activated", "exposed"],
        widget: QWidget,
        timeout: int,
    ) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None: ...
