from collections.abc import Callable
from types import TracebackType
from typing import Self, override

from _typeshed import Incomplete
from PySide6.QtCore import Signal

class _AbstractSignalBlocker:
    def __init__(self, timeout: int = ..., raising: bool = ...) -> None: ...
    def wait(self) -> None: ...
    def determine_signal_name(
        self, potential_signal_tuple: tuple[Signal, str]
    ) -> str: ...
    def get_callback_name(self, callback: Callable[..., Incomplete]) -> str: ...
    @staticmethod
    def get_signal_from_potential_signal_tuple(
        signal_tuple: tuple[Signal, str],
    ) -> Signal: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        type: type[BaseException] | None,
        value: BaseException | None,
        traceback: TracebackType | None,
    ) -> None: ...

class SignalBlocker(_AbstractSignalBlocker):
    def __init__(
        self,
        timeout: int = ...,
        raising: bool = ...,
        check_params_cb: Callable[..., Incomplete] = ...,
    ) -> None: ...
    def connect(self, signal: Signal) -> None: ...
    def get_params_as_str(self) -> str: ...
    timeout: int
    "Maximum time to wait for a signal to be triggered"
    signal_triggered: bool
    raising: bool
    args: list[Incomplete]

class SignalAndArgs:
    def __init__(self, signal_name: str, args: Incomplete) -> None: ...
    @override
    def __eq__(self, other: Incomplete) -> bool: ...

def get_ordinal_str(n: int) -> str: ...

class NoMatchingIndexFoundError(Exception): ...

class MultiSignalBlocker(_AbstractSignalBlocker):
    def __init__(
        self,
        timeout: int = ...,
        raising: bool = ...,
        check_params_cbs: list[Callable[..., Incomplete]] = ...,
        order: int = ...,
    ) -> None: ...
    def add_signals(self, signals: list[Signal | tuple[Signal, str]]) -> None: ...

class SignalEmittedSpy:
    def __init__(self, signal: Signal) -> None: ...
    def slot(self, *args: Incomplete) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(
        self,
        type: type[BaseException] | None,
        value: BaseException | None,
        traceback: TracebackType | None,
    ) -> None: ...
    def assert_not_emitted(self) -> None: ...

class CallbackBlocker:
    def __init__(self, timeout: int = ..., raising: bool = ...) -> None: ...
    def wait(self) -> None: ...
    def assert_called_with(self, *args: Incomplete, **kwargs: Incomplete) -> None: ...
    def __call__(self, *args: Incomplete, **kwargs: Incomplete) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        type: type[BaseException] | None,
        value: BaseException | None,
        traceback: TracebackType | None,
    ) -> None: ...

class SignalEmittedError(Exception): ...
class CallbackCalledTwiceError(Exception): ...
