[project]
name = "music_modify"
version = "2.0.0"
authors = [{ name = "Kyzan Hartwig" }]
description = "Music file tag editor"
readme = { file = "README.md", content-type = "text/markdown" }
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
keywords = ["mp3", "music", "tags"]
dependencies = ["PySide6>=6.9.0", "mutagen>=1.47.0"]
requires-python = ">= 3.13"

[build-system]
requires = ["setuptools>=80.8"]
build-backend = "setuptools.build_meta"

[project.scripts]
music_modify = "music_modify.music_modify:main"

[project.optional-dependencies]
test = [
  "pytest>=8.4.1",
  "pytest-qt>=4.5.0",
  "pytest-lazy-fixtures>=1.3.4",
  "pytest-cov>=6.2.1",
]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]

[tool.basedpyright]
reportAny = false
reportUnusedCallResult = false
reportUnknownMemberType = false
reportPrivateImportUsage = false
reportUnknownVariableType = false
reportUnknownArgumentType = false
reportExplicitAny = false
reportMissingTypeStubs = false
reportUnknownLambdaType = false
reportUnannotatedClassAttribute = false

[tool.ruff]
# Formatter wraps lines at a length of 80
line-length = 88
indent-width = 4
extend-exclude = ["ui_*.py"]

target-version = "py313"

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint]
select = [
  "E",    # pycodestyle error
  "F",    # pyflakes
  "ERA",  # commented out code
  "ANN",  # flake8 annotations
  "S",    # flake8 bandit
  "FBT",  # flake8 boolean trap
  "B",    # flake8 bugbear
  "A",    # flake8 builtins
  "COM",  # flake8 commas
  "C4",   # flake8 comprehensions
  "LOG",  # flake8 logging
  "PIE",  # flake8 pie (misc)
  "PYI",  # flake8 pyi (type stub files)
  "PT",   # flake8 pytest-style
  "Q",    # flake8 quotes
  "RET",  # flake8 return
  "SIM",  # flake8 simplify
  "TC",   # flake8 type checking
  "PTH",  # flake8 use pathlib
  "N",    # pep8 naming
  "PERF", # perflint
  "W",    # pycodestyle warning
  "UP",   # pyupgrade
  "PLC",  # pylint convention
  "PLE",  # pylint error
  "PLW",  # pylint warning
  "PLR",  # pylint refactor
  "C901", # mccabe complexity check
  "FURB", # refurb
  "RUF",  # ruff-specific
  "D",    # pydocstyle
]
ignore = [
  "N802",   # invalid function name (as function names are camelCase, not snake_case)
  "TC006",  # missing quotes around types in cast
  "COM812", # missing trailing commas
]

[tool.ruff.lint.per-file-ignores]
# "test*.py" = ["S101", "B011", "D", "PLR2004", "W505", "E501", "N806"]
"test*.py" = [
  "S101",    # use of assert
  "B011",    # using assert False
  "PLR2004", # magic value comparison
  "N806",    # non-lowercase variable in function
  "FBT",     # boolean values in calls
  "PLR0913", # too many args in function definition
]
"**.pyi" = [
  "A", # shadowing builtins
]

[tool.ruff.lint.pycodestyle]
max-doc-length = 88
# E501 reports lines that exceed 100
max-line-length = 100

[tool.ruff.lint.isort]
force-sort-within-sections = true

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.mccabe]
max-complexity = 12

[tool.coverage.report]
omit = ["src/music_modify/__main__.py", "src/music_modify/music_modify.py"]
