[project]
name = "music_modify"
version = "2.0.0"
authors = [{ name = "Kyzan Hartwig" }]
description = "Music file tag editor"
readme = { file = "README.md", content-type = "text/markdown" }
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
keywords = ["mp3", "music", "tags"]
dependencies = ["PySide6>=6.9.0", "mutagen>=1.47.0"]
requires-python = ">= 3.13"

[build-system]
requires = ["setuptools>=80.8"]
build-backend = "setuptools.build_meta"

[project.scripts]
music_modify = "music_modify.music_modify:main"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]

[tool.basedpyright]
reportAny = false
reportUnusedCallResult = false
reportUnknownMemberType = false
reportPrivateImportUsage = false
reportUnknownVariableType = false
reportUnknownArgumentType = false
reportExplicitAny = false
reportMissingTypeStubs = false
reportUnknownLambdaType = false

[tool.ruff]
# Formatter wraps lines at a length of 80
line-length = 88
indent-width = 4
extend-exclude = ["ui_*.py"]

target-version = "py313"

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint]
select = [
  "E",
  "F",
  "ERA",
  "ANN",
  "S",
  "FBT",
  "B",
  "A",
  "COM",
  "C4",
  "LOG",
  "PIE",
  "PYI",
  "PT",
  "Q",
  "RET",
  "SIM",
  "TC",
  "PTH",
  "N",
  "PERF",
  "W",
  "UP",
  "PLC",
  "PLE",
  "PLW",
  "PLR",
  "C901",
  "FURB",
  "RUF",
  "D",
]
ignore = ["N802", "TC006", "COM812"]

[tool.ruff.lint.per-file-ignores]
"test*.py" = ["S101", "B011", "D"]
"**.pyi" = ["A", "COM812"]
"widgets_complete.py" = ["PLC", "PLR", "C901", "D"]

[tool.ruff.lint.pycodestyle]
max-doc-length = 88
# E501 reports lines that exceed 100
max-line-length = 100

[tool.ruff.lint.isort]
force-sort-within-sections = true

[tool.ruff.lint.pydocstyle]
convention = "google"
